#pragma include_alias("pch.h", "../pch.h")
#include "pch.h"
#include "File.h"

namespace YBWLib2 {
	YBWLIB2_DYNAMIC_TYPE_IMPLEMENT_CLASS(ISeekableFile, YBWLIB2_API);
	YBWLIB2_DYNAMIC_TYPE_IMPLEMENT_CLASS(IInputFile, YBWLIB2_API);
	YBWLIB2_DYNAMIC_TYPE_IMPLEMENT_CLASS(IOutputFile, YBWLIB2_API);

	void YBWLIB2_CALLTYPE File_RealInitGlobal() noexcept {
		YBWLIB2_DYNAMIC_TYPE_REALINIT_CLASS(ISeekableFile, IReferenceCountedObject);
		YBWLIB2_DYNAMIC_TYPE_REALINIT_CLASS(IInputFile, ISeekableFile);
		YBWLIB2_DYNAMIC_TYPE_REALINIT_CLASS(IOutputFile, ISeekableFile);
	}

	void YBWLIB2_CALLTYPE File_RealUnInitGlobal() noexcept {
		YBWLIB2_DYNAMIC_TYPE_REALUNINIT_CLASS(IOutputFile);
		YBWLIB2_DYNAMIC_TYPE_REALUNINIT_CLASS(IInputFile);
		YBWLIB2_DYNAMIC_TYPE_REALUNINIT_CLASS(ISeekableFile);
	}
}
